### ISSUE TITLE
Support for setting values inline (no yaml file)

### ISSUE THREAD

**Issue by jmdots** [linkyard/concourse-helm-resource#104]
I would like to avoid having separate yaml files for my helm chart overrides. Also, individual key-value sets is pretty tedious.

Would you consider implementing something like this (see ` override_values_objects`)? A map-merge would happen in the order objects are listed. This stage would precede the `override_values` so that key-value changes could be the last operation. Maybe you can think of a better name for it. :)

```yaml
resource_types:
- name: helm
  source:
    repository: linkyard/concourse-helm-resource
  type: docker-image
resources:
- name: chaoskube
  source:
    repos:
    - name: stable
      url: https://kubernetes-charts.storage.googleapis.com
  type: helm
jobs:
  plan:
  - put: chaoskube
    params:
      chart: stable/chaoskube
      override_values_objects:
      - config:
          annotations: ''
          dryRun: false
          interval: 5m
          labels: release!=chaoskube
          namespaces: '!kube-system'
        priorityClassName: common-high
      - priorityClassName: change-my-mind
```
