### ISSUE TITLE
Failed to ping registry https://https/v2/

### ISSUE THREAD

**Issue by kevcodez** [linkyard/concourse-helm-resource#106]
When trying to run the helm task, I get the following exception:

> failed to ping registry: 2 error(s) occurred:
> 
> * ping https: Get https://https/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
> * ping http: Get http://https/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

My pipeline:

```yml
---
resource_types:
- name: helm
  type: docker-image
  source:
    repository: https://github.com/linkyard/concourse-helm-resource

resources:
...
- name: backend-helm
  type: helm
  source:
    cluster_url: https://<cluster-ip>
    cluster_ca: <cert>
    token: <token>

jobs:
...
- put: backend-helm
    params:
      chart: git-repo-backend/helm/Chart.yaml
      values: git-repo-backend/values.yaml
```

Not sure what it is trying to ping and why. Would appreciate any help.

**Comment by kevcodez** [comment]
Ok, nevermind, I'm an idiot. If you just use the sample provided in the README for the resource_type, it works fine:

```
resource_types:
- name: helm
  type: docker-image
  source:
    repository: https://github.com/linkyard/concourse-helm-resource
```

I put the entire Github Link as repository source, which is obviously nonsense, since it is referring to a docker image.
