### ISSUE TITLE
Secret vales being logged in cleartext

### ISSUE THREAD

**Issue by TimJones** [linkyard/concourse-helm-resource#24]
We use Vault with Concourse to configure deployments of Helm apps with passwords/tokens/etc without them being in cleartext in the pipeline. Using `values_override` means they get logged as so:
```Running command helm upgrade tools-chatbot -f /tmp/build/put/project-git/charts/values.yaml --set tag=62690800a1869f78ca058e83438b91f41c56968f --set 'config.token=<SUPER_SECRET_TOKEN>' project-git/charts/chatbot | tee /tmp/log```

I would very much prefer to be able to hide these values.

The best option would be to include a new `hide` option in the `values_override` list:
```
values_override:
  - key: tag
    file: project-git/.git/ref
  - key: config.token
    value: ((vault-secret-value))
    hide: true
```

Which would give an output similar to:
```Running command helm upgrade tools-chatbot -f /tmp/build/put/project-git/charts/values.yaml --set tag=62690800a1869f78ca058e83438b91f41c56968f --set 'config.token=*REDACTED*' project-git/charts/chatbot | tee /tmp/log```

Another, maybe simpler, option could be to have a flag to disable the `echo "Running command $helm_cmd"` in `helm_install()` and `helm_upgrade()`.
