### ISSUE TITLE
Support for specifying a kubeconfig file instead of separate params

### ISSUE THREAD

**Issue by wendorf** [linkyard/concourse-helm-resource#36]
When using a tool like https://github.com/kubernetes/kops, a complete kubeconfig is generated. Instead of decomposing it into URLs and credentials to pass to the concourse-helm-resource, I'd like to be able to specify a file like this:

```
resources:
- name: mysql-helm
  type: helm
  source:
    release: custom-mysql

- name: kubeconfig
  type: s3
  source:
    bucket: mybucket
    access_key_id: ((s3-access-key))
    secret_access_key: ((s3-secret))

jobs:
- name: deploy-mysql
  plan:
    - get: kubeconfig
    - put: mysql-helm
      params:
        kubeconfig_file: kubeconfig/file
        chart: stable/mysql
```
