### ISSUE TITLE
hide option not working anymore.

### ISSUE THREAD

**Issue by maandr** [linkyard/concourse-helm-resource#80]
Lately the `hide` option does not work for me anymore, even when providing new `type: string` along with it.

```yaml
    - put: k8s
      params:
        chart: git/my-helm-chart
        values: git/my-helm-chart/values.yaml
        namespace: ((k8s_namespace))
        release: my-release
        override_values:
        - key: database.password
          value: ((database_password))
          type: string
          hide: true
```
This configuration still prints the values of `database.password` in the logs.
