### ISSUE TITLE
Check fails: unexpected end of JSON input

### ISSUE THREAD

**Issue by rubenv** [linkyard/concourse-helm-resource#81]
I'm getting the very cryptic `unexpected end of JSON input` error from check.

I'm using a config like this one, which shouldn't be too special:

```
    - name: helm
      type: helm
      source:
          cluster_url: ((kubernetes-cluster-url))
          cluster_ca: ((kubernetes-cluster-ca))
          admin_key: ((kubernetes-admin-key))
          admin_cert: ((kubernetes-admin-cert))
          namespace: datahub
          release: datahub
```

This config works for deploying charts, so I think it's correct.

Is there any way to get more debug output from check? Anything I could do to help figure this out?
